### ISSUE TITLE
No longer works for Pathfinder 2e ruleset

### ISSUE THREAD

**Issue by roguedevjake** [vtt-lair/foundry-group-initiative#13]
Tested on fresh world with no other modules or settings set. 
Foundry Version: 0.8.9

1. Clicking roll group or roll group npcs buttons roll one npc at a time
2. While group rolling sometimes npcs are grouped together, sometimes they are split into multiple groups
3. The group's initiative is set by the highest individual roll in the group

**Comment by vtt-lair** [comment]
Hey @roguedevjake, thanks for letting me know. I'm releasing a new version later this week. Would it be possible for you to check against that version as well. I fixed a few bugs and hopefully it'll sort yours out too.

I'll comment here when the new version is released.

**Comment by bbollig** [comment]
Experienced the same issue last night while testing out the mod to see if I could make use of it for my game since I had a big combat coming with multiple groups competing against each other. In one case, I had a PC grouped under a Monster's initiative; in another, it was mixing two different groups of Monster NPCs at multiple initiatives; also, some Monsters who could have been nested in other places had stand-alone turns in the tracker. 

There were other issues as well but it was hardly a clean test. I wanted to chime in because I could put this module to great use. Looking forward to the next release to try it again.

**Comment by AnnoUltima** [comment]
Hi, just commenting that I am also experiencing this problem as of December 23rd.

**Comment by vtt-lair** [comment]
I'll have to investigate the PF2E system, as it's initiative rolls (and honestly all it's rolls) works differently than the DnD 5e or most other systems.

I had to do a huge refactor on the Let Me Roll That For You module specifically because PF2E calls rolls differently. Will try and get to this refactor in the next week or 2. Sorry for the delay.

**Comment by Ghilteras** [comment]
@vtt-lair this seems still broken for pf2e system, any chance we can fix this?

**Comment by vtt-lair** [comment]
I've just had a look at this. And what seems to happen with PF2e vs other systems, when the initiative is rolled, the combact tracker isn't update immediately. This is possibly due to the modal for PF2e's iniative showing and only rolling on that button press.

However, I would have expected that since I'm waiting for results (i.e. I'm waiting for the initiative rolls) that the combact tracker would be updated. In other systems, the combat tracker is updated and reflects as soon as the roll is cast, for PF2e it seems to only register the roll at a later stage.

As such when I try and update the rest of the combatants that has been grouped together, it just updates it to an empty initiative, since the rolled combatant's initiative hasn't actually been updated yet.

No idea what to do here unfortunately.

**Comment by Ghilteras** [comment]
Have you tried asking the pf2e system devs on discord? I'm pretty sure they can help you figure out how to make this working again. They are super helpful
